---
- name: 'create {{ nginx_proxy_name }} docker-compose directory'
  file:
    path: '{{ nginx_proxy_compose_path }}'
    state: directory

- name: 'create {{ nginx_proxy_name }} docker-compose.yml'
  template:
    dest: '{{ nginx_proxy_compose_path }}/docker-compose.yml'
    src: '../templates/nginx-proxy.docker-compose.j2.yml'

- name: 'run {{ nginx_proxy_name }} docker-compose service'
  docker_service:
    project_name: '{{ nginx_proxy_name }}'
    project_src: '{{ nginx_proxy_compose_path }}'
  when: docker__ansible_python_interpreter is not defined

- name: 'run {{ nginx_proxy_name }} docker-compose service (using custom python interpreter)'
  vars:
    ansible_python_interpreter: '{{docker__ansible_python_interpreter}}'
  docker_service:
    project_name: '{{ nginx_proxy_name }}'
    project_src: '{{ nginx_proxy_compose_path }}'
  when: docker__ansible_python_interpreter is defined
